### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 1, 3, 3], expected input[1, 301, 512, 512] to have 1 channels, but got 301 channels instead

### ISSUE THREAD

**Issue by Palashio** [kilgore92/PyTorch-UNet#2]
when I use your UNet with these specifications: 

```python
model = UNet(n_channels=270,
             num_classes=2,
             mode='3D',
             use_pooling=False
             )
```

my torch tensor size is (1, 270, 512, 512).

with this training script: 

```python
def train():
    criterion = dice_loss
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    num_steps_train = len(train_loader)
    
    print(num_steps_train)
    
    for epoch in range(epochs):
        print(' - training - ')
        model.train()
        for i, (images, masks) in enumerate(train_loader):
            images = images.to(device)
            masks = masks.to(device)
            outputs = model(images)
            loss = criterion(outputs, masks)
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
```

I get this error:` RuntimeError: Given groups=1, weight of size [64, 1, 3, 3], expected input[1, 301, 512, 512] to have 1 channels, but got 301 channels instead`

Looking at the frames it's getting this error at the `outputs = model(images)` step. Any idea why?

**Comment by Palashio** [comment]
This is what my __getitem__ looks like in dataset class:

```python
def __getitem__(self, index):
    image = torch.from_numpy(sitk.GetArrayFromImage(sitk.ReadImage(self.orig[index])))
    mask = torch.from_numpy(sitk.GetArrayFromImage(sitk.ReadImage(self.segment[index])))
    return image, mask`
```
Here's how I'm loading the data:
```python
 train_loader = DataLoader(dataset=Dataset(partition['orig'], partition['segment']), 
                          batch_size = batch_size, shuffle = True)
```

partition just has a original / segmented image list (which is the list of paths to images that're original vs the mask.

**Comment by ishaanb92** [comment]
Hi Palash,

PyTorch expects data to be in the shape of (Batch Size, Number of Channels, D, H, W) -- it mistakes the depth of your image to be the number of channels. To fix this you need to reshape your image with torch.reshape(image, shape=(batch_size, 1, depth, width, height) to create an artificial channel. Please refer: https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html?highlight=conv3d#torch.nn.Conv3d

Cheers,
Ishaan

**Comment by Palashio** [comment]
So, I tried all of the above. Let's say my images are of size (128, 128, 128). I tried resizing them using torch to both `(1, 128, 128, 128)` and ` (1, 1, 128, 128)` and neither of them worked. My batch_size is 1 so that's why it is 1, 1.

This is the UNet that i'm working with:
```python

model = UNet(n_channels=1,
             mode='3D',
             use_pooling=False
             )
```

I also tried changing n_channels = 128. 

Could you guide me onto what the tensor shapes should be for my case? I can't seem to get this to work eventhough my dimensions should be aligning.

**Comment by Palashio** [comment]
for example, when i reshape to (1, 128, 128, 128) I get 
```python
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 1, 3, 3], but got 5-dimensional input of size [1, 1, 128, 128, 128] instead
```

when i reshape to (1, 1, 128, 128, 128) I get this: 
```python
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 1, 3, 3], but got 5-dimensional input of size [1, 1, 128, 128, 128] instead
```

do i need to add the num_classes? (the masks are just 1's and 0's). change the number of channels?

**Comment by Palashio** [comment]
so i changed it to , 
``` python
model.forward(images)
``` 
to do a forward pass but it still happens.

**Comment by ishaanb92** [comment]
Yes, your number of channels is 1 (which explains the "extra" dimension you add via reshape). If your batch size is 1 then the correct input shape is (1, 1, 128, 128, 128). num_classes should be 2 since you have binary labels. Could you tell me what line gives you this error? (It should come from either model.py or blocks.py)

**Comment by Palashio** [comment]
hi @kilgore92 i got it to work. there were just smaller issues on my side.

**Comment by ishaanb92** [comment]
Great! I'll close the issue. Please open issues/let me know if the code can be improved in any way. 

Cheers,
Ishaan

**Comment by Palashio** [comment]
so when i do .forward() the number of channels is equal to 2 when the input channel number is equal to 1 any idea why / how i can compute loss between the two?

**Comment by Palashio** [comment]
so if i do `outputs.size()` I get (1, 2, 128, 128) when my input was (1, 1, 128, 128). Is it correct? If so, how do I compute the loss between them?
